proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastros.urls')),
    path('', include('tickets.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password-done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from tickets.apis import SolicitacaoAPIView
from tickets.views import NovaSolicitacao, SolicitacaoView, AssinarView, DetalheTicketView

urlpatterns = [
    path('tickets/', login_required(SolicitacaoView.as_view()), name='lista-solicitacao-ticket'),
    path('tickets/novo', NovaSolicitacao.as_view(), name='nova-solicitacao-ticket'),
    path('tickets/api', SolicitacaoAPIView.as_view(), name='solicitacao-api-ticket'),
    path('tickets/assinar/<id>/', login_required(AssinarView.as_view()), name='assinar-solicitacao-ticket'),
    path('tickets/detalhe/<id>/', login_required(DetalheTicketView.as_view()), name='detalhe-solicitacao-ticket'),
]

tickets/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone

from tickets.utils import MongoHandler


class Categoria(models.Model):

    descricao = models.CharField(max_length=255)
    ativo = models.BooleanField(default=True)

    class Meta:
        ordering = ('descricao', )

    def __str__(self):
        return self.descricao


class Solicitacao(models.Model):

    STATUS_NEW = 'new'
    STATUS_ONGOING = 'ongoing'
    STATUS_CLOSED = 'closed'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Novo'),
        (STATUS_ONGOING, 'Em andamento'),
        (STATUS_CLOSED, 'Encerrado'),
        (STATUS_CANCELED, 'Cancelado'),
    )

    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    nome = models.CharField(max_length=120)
    email = models.EmailField(verbose_name='E-mail')
    assunto = models.CharField(max_length=80)
    descricao = models.TextField(verbose_name='Descrição')
    arquivo = models.FileField(upload_to='solicitacoes', null=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default=STATUS_NEW)
    atendente = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    data_solicitacao = models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')
    ultima_atualizacao = models.DateTimeField(auto_now=True, verbose_name='Última Atualização')

    class Meta:
        ordering = ('-ultima_atualizacao', )
        verbose_name = 'Solicitação'
        verbose_name_plural ='Solicitações'

    def __str__(self):
        return f'TICKET{self.pk:04d}'

    # def save(self, *args, **kwargs):
    #
    #     if self.pk:
    #         pass
    #
    #     super().save(*args, **kwargs)

    def registrar_atendente(self, user):

        self.status = self.STATUS_ONGOING
        self.atendente = user
        self.save()

        interacao_obj = Interacao.objects.create(
            solicitacao=self,
            tipo=Interacao.TIPO_ASSIGNED,
            descricao=f'Solicitação assinada para o atendente {user.get_full_name()}',
            atendente=user,
        )

        interacao_obj.send_mail_message()

        return True

    def registrar_resposta(self, user, mensagem):

        self.atendente = user
        self.save()

        interacao_obj = Interacao.objects.create(
            solicitacao=self,
            tipo=Interacao.TIPO_TEAM_RESPONSE,
            descricao=f'Nova resposta: {mensagem}',
            atendente=user,
        )

        interacao_obj.send_mail_message()

        return True

    def cancelar(self, user, motivo):

        self.atendente = user
        self.status = self.STATUS_CANCELED
        self.save()

        interacao_obj = Interacao.objects.create(
            solicitacao=self,
            tipo=Interacao.TIPO_STATUS_CHANGE,
            descricao=f'Ticket cancelado. Motivo: {motivo}',
            atendente=user,
        )

        interacao_obj.send_mail_message()

        return True

    def finalizar(self, user, motivo):

        self.atendente = user
        self.status = self.STATUS_CLOSED
        self.save()

        interacao_obj = Interacao.objects.create(
            solicitacao=self,
            tipo=Interacao.TIPO_STATUS_CHANGE,
            descricao=f'Ticket fechado. Motivo: {motivo}',
            atendente=user,
        )

        interacao_obj.send_mail_message()

        return True


class Interacao(models.Model):

    TIPO_ASSIGNED = 0
    TIPO_TEAM_RESPONSE = 1
    TIPO_REQUESTER_RESPONSE = 2
    TIPO_STATUS_CHANGE = 3

    TIPO_CHOICES = (
        (TIPO_ASSIGNED, 'Assinado para o atendente'),
        (TIPO_TEAM_RESPONSE, 'Resposta do time'),
        (TIPO_REQUESTER_RESPONSE, 'Resposta do solicitante'),
        (TIPO_STATUS_CHANGE, 'Mudança de status')
    )

    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.CASCADE, related_name='interacoes')
    tipo = models.PositiveSmallIntegerField(choices=TIPO_CHOICES)
    descricao = models.TextField()
    atendente = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    data_interacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-data_interacao',)
        verbose_name = 'Interação'
        verbose_name_plural = 'Interações'

    def __str__(self):

        return f'{self.pk}'

    def send_mail_message(self):

        subject = f'{self.solicitacao} - Nova interação - {self.get_tipo_display()}'

        send_mail(
            subject=subject,
            message=self.descricao,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.solicitacao.email]
        )

        email_data = {
            'subject': subject,
            'recipient': self.solicitacao.email,
            'message': self.descricao,
            'date': timezone.now()
        }

        mg = MongoHandler('tickets')
        mg.insert('emails', email_data)

tickets/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset, Layout, ButtonHolder, Submit
from django import forms

from tickets.models import Solicitacao


class NovaSolicitacaoForm(forms.ModelForm):

    class Meta:
        model = Solicitacao
        fields = ['categoria', 'nome', 'email', 'assunto', 'descricao', 'arquivo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Dados pessoais',
                'nome',
                'email'
            ),
            Fieldset(
                'Mensagem',
                'categoria',
                'assunto',
                'descricao',
                'arquivo'
            ),
            ButtonHolder(
                Submit('submit', 'Enviar solicitação', css_class='btn btn-primary')
            )
        )

tickets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View

from tickets.forms import NovaSolicitacaoForm
from tickets.models import Interacao, Solicitacao
from tickets.tables import SolicitacaoTable


class NovaSolicitacao(View):

    def get(self, request):

        form = NovaSolicitacaoForm

        return render(request, 'tickets/form.html', {'form': form})

    def post(self, request):

        form = NovaSolicitacaoForm(request.POST, request.FILES)

        if form.is_valid():

            obj = form.save(commit=True)
            obj.save()

            interacao = Interacao.objects.create(solicitacao=obj, tipo=Interacao.TIPO_STATUS_CHANGE, descricao='Solicitação aberta')
            interacao.send_mail_message()

            return redirect('cidades-list')

        return render(request, 'tickets/form.html', {'form': form})


class SolicitacaoView(View):

    def get(self, request):

        qs = Solicitacao.objects.all().order_by('id')

        table = SolicitacaoTable(qs)

        context = {
            'table': table
        }
        return render(request, 'tickets/lista_tickets.html', context)

    def post(self, request):

        id = request.POST.get('id')
        solicitacao = get_object_or_404(Solicitacao, pk=id)

        tipo = request.POST.get('tipo')
        if tipo == 'resposta':
            mensagem = request.POST.get('mensagem', '')
            solicitacao.registrar_resposta(request.user, mensagem)

        elif tipo == 'finalizar':
            motivo = request.POST.get('motivo', '')
            operacao = request.POST.get('operacao', '')
            if operacao == 'c':
                solicitacao.cancelar(request.user, motivo)
            else:
                solicitacao.finalizar(request.user, motivo)

        return redirect('lista-solicitacao-ticket')


class AssinarView(View):

    def get(self, request, id):

        solicitacao = get_object_or_404(Solicitacao, pk=id)

        solicitacao.registrar_atendente(request.user)

        return redirect('lista-solicitacao-ticket')


class DetalheTicketView(View):

    def get(self, request, id):

        solicitacao = get_object_or_404(Solicitacao, pk=id)

        return render(request, 'tickets/detalhe.html', {'obj': solicitacao} )

tickets/templates/tickets/actions.html
<div class="btn-group" role="group" aria-label="Basic example">
  <a href="{% url 'detalhe-solicitacao-ticket' record.id %}" class="btn btn-success">V</a>
    {% if not record.atendente %}
  <a href="{% url 'assinar-solicitacao-ticket' record.id %}" class="btn btn-primary">A</a>
    {% endif %}
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#respostaModal" data-id="{{ record.id }}">R</button>
    {% if record.status == 'ongoing' %}
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#finalizarModal" data-id="{{ record.id }}">F</button>
    {% endif %}
</div>

tickets/templates/tickets/detalhe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
    <h1>Detalhe do ticket: {{ obj }}</h1>

    <ul>
        <li>Categoria: {{ obj.categoria }}</li>
        <li>Nome: {{ obj.nome }}</li>
        <li>Email: {{ obj.email }}</li>
        <li>Assunto: {{ obj.assunto }}</li>
        <li>Descrição: {{ obj.descricao }}</li>
        <li>Arquivo: {% if obj.arquivo %}<a href="/{{ obj.arquivo.url }}">Download</a>{% else %}-{% endif %}</li>
        <li>STATUS: {{ obj.get_status_display }}</li>
        <li>ATENDENTE: {{ obj.atendente }}</li>
        <li>Data da Solicitação: {{ obj.data_solicitacao }}</li>
        <li>Última atualização: {{ obj.ultima_atualizacao }}</li>
    </ul>

<h2>Histórico</h2>

{% for interacao in obj.interacoes.all %}

    <ul>
        <li>Tipo: {{ interacao.get_tipo_display }} </li>
        <li>Descrição: {{ interacao.descricao }} </li>
        <li>Atendente: {{ interacao.atendente }} </li>
        <li>Data: {{ interacao.data_interacao }} </li>
    </ul>

{% endfor %}


{% endblock %}

tickets/templates/tickets/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
    <h1>Nova solicitação:</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>

{% endblock %}

tickets/templates/tickets/lista_tickets.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}

{% block conteudo %}
<h1>Tickets:</h1>
<p>
    <a class="btn btn-primary" href="{% url 'nova-solicitacao-ticket' %}">Novo ticket</a>
</p>
<div>
    {% render_table table %}
</div>

<!-- Modal -->
<div class="modal fade" id="respostaModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enviar Resposta</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Mensagem</span>
                        </div>
                        <textarea class="form-control" aria-label="Mensagem" name="mensagem" id="mensagem"></textarea>
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="tipo" id="tipo" value="resposta">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="finalizarModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cancelar/Finalizar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <select name="operacao" class="form-control" >
                            <option value="c">Cancelar</option>
                            <option value="f">Finalizar</option>
                        </select>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Motivo</span>
                        </div>

                        <textarea class="form-control" aria-label="Motivo" name="motivo" id="motivo"></textarea>
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="tipo" id="tipo" value="finalizar">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $('#respostaModal').on('show.bs.modal', function(e) {

    //get data-id attribute of the clicked element
    var ticketId = $(e.relatedTarget).data('id');

    //populate the textbox
    $(e.currentTarget).find('input[name="id"]').val(ticketId);
});
    $('#finalizarModal').on('show.bs.modal', function(e) {

    //get data-id attribute of the clicked element
    var ticketId = $(e.relatedTarget).data('id');

    //populate the textbox
    $(e.currentTarget).find('input[name="id"]').val(ticketId);
});
</script>

{% endblock %}